services:

  filezilla:
    image: jlesage/filezilla
    container_name: filezilla
    ports:
      - "5800:5800"
    volumes:
      - ./config:/config:rw
      - ./storage:/storage:rw
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - TZ=Europe/Madrid
      - UMASK=0022
      - LANG=es_ES.UTF-8
      - DARK_MODE=0  #1
      - WEB_AUTHENTICATION=0  #1  
      - WEB_AUTHENTICATION_USERNAME=admin
      - WEB_AUTHENTICATION_PASSWORD=p4ssw0rd
    restart: unless-stopped

